language: python
python:
    - "3.5"
    - "3.6"
    - "nightly"
    
before_install:
    - pip install -r requirements.txt
    
    
install:
    - python setup.py install
    
    
script:
    - python pyHCA/tests/tests_hca.py
    - python pyHCA/tests/tests_seghca.py